# Generated by Django 5.1.7 on 2025-03-16 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('client_vat', models.CharField(blank=True, max_length=50, null=True)),
                ('freelancer_vat', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acount_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_vat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freelancer_vat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_transactions', to='contract.contract')),
                ('contract_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_transactions', to='contract.contract')),
                ('contract_freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_transactions', to='contract.contract')),
                ('contract_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_transactions', to='contract.contract')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod')),
            ],
        ),
    ]
