# Generated by Django 5.1.7 on 2025-03-16 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='client_vat_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='freelancer_vat_amount',
        ),
    ]
