# Generated by Django 5.1.7 on 2025-03-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_terms', models.TextField()),
                ('dedline', models.PositiveIntegerField(default=0)),
                ('budget', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_state', models.CharField(choices=[('pending', 'Pending'), ('aproved', 'Aproved'), ('canceled', 'Canceled')], default='pending', max_length=20)),
            ],
        ),
    ]
