# Generated by Django 5.1.7 on 2025-03-14 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
        ('freelancia_back_end', '0007_alter_project_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('aproved', 'Aproved'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('freelancer', 'client', 'project')},
        ),
    ]
