# Generated by Django 5.1.7 on 2025-04-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_attachment_description_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('Accepted', 'Accepted'), ('canceled', 'Canceled'), ('Completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
