# Generated by Django 5.1.7 on 2025-04-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_alter_contract_contract_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='dedline',
            new_name='deadline',
        ),
    ]
