# Generated by Django 5.1.7 on 2025-04-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_rename_dedline_contract_deadline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set(),
        ),
    ]
