# Get Login Tockens
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}
###
# Refresh the Login tocken
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0MTk3NDE5MCwiaWF0IjoxNzQxODg3NzkwLCJqdGkiOiI3MWE3OWVlOTA5ZmQ0OWUxOWZlYzYwYzU5ZTZlMmViZiIsInVzZXJfaWQiOjF9.TUbwgtRJT_8uehDncHz08NQXw378DpyDbk9j1HOpWQk"
}
###
POST http://localhost:8000/logout/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxOTc5MzQ2LCJpYXQiOjE3NDE5NzkwNDYsImp0aSI6IjZjNTBmZThmNzZhMDQzNTlhNzVlMzVmODUwNWVkMmU4IiwidXNlcl9pZCI6MX0.o_D0TYR-Y_E-DnS_29eBTF1XZodBHlyQ8WrtScinuMo

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0MzI3NTA0NiwiaWF0IjoxNzQxOTc5MDQ2LCJqdGkiOiI5N2FjN2IxOTQ3ZGQ0MDA1YmIwOThiZTYwYjIwZjMwMyIsInVzZXJfaWQiOjF9.P7v_iwi0BPFqzYntrVscm-1G3tPdwEYTcYobg-nBjnI"
}
###
POST http://localhost:8000/auth-token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}
###
GET http://127.0.0.1:8000/user/1/   HTTP/1.1
Authorization: Token 59b080dca01c0731d06a9a3b2a84e47396ebc48f