# Generated by Django 5.1.7 on 2025-03-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancia_back_end', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('title', 'user')},
        ),
    ]
