# Generated by Django 5.1.7 on 2025-03-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancia_back_end', '0002_rename_address_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
