# Generated by Django 5.1.7 on 2025-03-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancia_back_end', '0002_speciality_user_speciality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name_plural': 'Specialities'},
        ),
    ]
