# Generated by Django 5.1.7 on 2025-03-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancia_back_end', '0003_alter_speciality_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(related_name='users', to='freelancia_back_end.skill'),
        ),
    ]
