# Generated by Django 5.1.7 on 2025-03-12 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancia_back_end', '0003_alter_proposal_attachment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('user', 'project')},
        ),
    ]
