# Generated by Django 5.1.7 on 2025-03-19 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancia_back_end', '0003_alter_speciality_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('Proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='freelancia_back_end.proposal')),
            ],
        ),
    ]
