# Generated by Django 5.1.7 on 2025-03-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancia_back_end', '0003_alter_certificate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
