# Generated by Django 5.1.7 on 2025-03-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancia_back_end', '0004_alter_proposal_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='required_skills',
            new_name='skills',
        ),
    ]
