# Generated by Django 5.1.7 on 2025-04-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancia_back_end', '0004_user_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
