# Generated by Django 5.1.7 on 2025-03-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancia_back_end', '0005_rename_required_skills_project_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_state',
            field=models.CharField(choices=[('open', 'Open'), ('ongoing', 'Ongoing'), ('canceled', 'Canceled'), ('contract canceled and reopened', 'Contract Canceled And Reopened'), ('finished', 'Finished')], default='open', max_length=50),
        ),
    ]
